id: P006825
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:07.200086
source_metadata:
  id: bdr:W1CZ1108
  title: སྟོབས་བཞིའི་བཤགས་པ་
  author: ''
  volumes:
    63f23fff9d904e479a9e1030ffccb16f:
      image_group_id: I1CZ1378
      title: ''
      volume_number: 1
      total_pages: 14
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
